#!/usr/bin/env bash
# ToastService Test Script
# 
# This script demonstrates the ToastService by triggering various notifications
# through the services that now have toast support enabled.

echo "==================================="
echo "ToastService Test Script"
echo "==================================="
echo ""
echo "Prerequisites:"
echo "  - quickshell must be running with shell.qml"
echo "  - ToastService is now integrated and active"
echo ""
echo "This script will trigger toasts through actual service interactions:"
echo ""

echo "1. Testing NetworkService toasts:"
echo "   Run: nmcli radio wifi off"
echo "   Run: nmcli radio wifi on"
echo "   (Should show 'Wi-Fi Disabled' and 'Wi-Fi Enabled' toasts)"
echo ""

echo "2. Testing AudioService toasts:"
echo "   - Mute/unmute audio output"
echo "   - Mute/unmute audio input"
echo "   (Should show toast notifications)"
echo ""

echo "3. Testing NotificationService toast:"
echo "   Toggle Do Not Disturb in settings:"
echo "   QsCommons.Settings.data.notifications.doNotDisturb = true"
echo "   QsCommons.Settings.data.notifications.doNotDisturb = false"
echo ""

echo "4. Testing ColorSchemeService toast:"
echo "   Toggle dark mode in settings:"
echo "   QsCommons.Settings.data.colorSchemes.darkMode = false"
echo "   QsCommons.Settings.data.colorSchemes.darkMode = true"
echo ""

echo "5. Testing BluetoothService toasts:"
echo "   - Enable/disable Bluetooth adapter"
echo "   (Should show toast notifications)"
echo ""

echo "6. Direct ToastService API test:"
echo "   You can also test directly via quickshell console:"
echo ""
echo "   QsServices.ToastService.showNotice('Test Notice', 'This is a notice')"
echo "   QsServices.ToastService.showWarning('Test Warning', 'This is a warning')"
echo "   QsServices.ToastService.showError('Test Error', 'This is an error')"
echo ""

echo "7. Queue management test (rapid toasts):"
echo "   Run multiple toasts rapidly to test queue:"
echo ""
echo "   for (var i = 0; i < 5; i++) {"
echo "     QsServices.ToastService.showNotice('Toast ' + i, 'Message ' + i)"
echo "   }"
echo ""
echo "   With replaceOnNew=true (default): only last toast shows"
echo "   With replaceOnNew=false: all toasts queue and show sequentially"
echo ""

echo "==================================="
echo "Toast Settings (Settings.data.toast)"
echo "==================================="
echo ""
echo "Available settings:"
echo "  - enabled: true/false"
echo "  - location: 'top', 'top_right', 'top_left', 'bottom', 'bottom_right', 'bottom_left'"
echo "  - replaceOnNew: true/false (cancel current toast for new ones)"
echo "  - maxQueueSize: 10 (maximum queued toasts per screen)"
echo "  - overlayLayer: false (use Overlay vs Top layer)"
echo "  - monitors: [] (empty = all monitors, or specify monitor names)"
echo ""

echo "Change location:"
echo "  QsCommons.Settings.data.toast.location = 'bottom_right'"
echo ""

echo "Test replaceOnNew behavior:"
echo "  QsCommons.Settings.data.toast.replaceOnNew = false"
echo "  (Now rapid toasts will queue instead of replacing)"
echo ""

echo "==================================="
echo "Expected Visual Results"
echo "==================================="
echo ""
echo "✓ Toast appears in configured corner (default: top_right)"
echo "✓ Icon color matches type (notice=white, warning=primary, error=red)"
echo "✓ Border color matches type"
echo "✓ Smooth fade-in with scale animation"
echo "✓ Auto-dismisses after duration (notice=3s, warning=4s, error=5s)"
echo "✓ Click anywhere on toast to dismiss immediately"
echo "✓ Bar-aware margins (no overlap with bar)"
echo "✓ Sequential display (one toast at a time)"
echo ""

echo "==================================="
echo "Test Complete"
echo "==================================="
